package api.item
import model.Item
import play.api.i18n.Lang.logger

import scala.concurrent.{ExecutionContext, Future}
import javax.inject.Inject


// Inject() permet d'injecter des dépendances dans une classe
class ItemRepository @Inject()(implicit ec: ExecutionContext) {

  // Simuler une base de données en mémoire
  // La liste des items
  // Le projet est trop petit pour avoir besoin d'une vraie base de données
  private var items: List[Item] = List(
    Item("1", "Jean", "Valeurs exprimées en kg CO2e émis par produit comprenant la fabrication, la distribution et l’usage. La production de jeans a un bilan carbone élevé en raison de la culture intensive du coton, de la teinture, de la consommation d'eau et de l'énergie dans la fabrication, ainsi que du transport. Opter pour des jeans durables, recyclés ou de seconde main et réduire la surconsommation de vêtements peut contribuer à atténuer leur impact environnemental.", +80, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1701994633/njqh5jahq6vour3govi9.png", "24,56 kg CO2e / unité"),
    Item("2", "Arbre", "Offrant une ombre protectrice et un effet rafraîchissant", -70, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1702006872/o15sjuzkqsxkjxb62ohj.png", "Absorbe environ 25 kg de CO2 par an."),
    Item("3", "TGV", "Un TGV rejette en moyenne 1,7g par km. C'est entre 82g et 107g par km pour une voiture qui n'est pas électrique - en fonction des modèles - et entre 73g et 250 g par km pour l’avion. Prenons un exemple concert : un voyage de Paris à Marseille. Si, en TGV, les émissions de CO2 pour chaque passager est de 1,7 kg par kilomètre, la voiture en rejettera, elle, 127. C'est donc 74 fois plus que le train avec un seul voyageur.", -20, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1702006712/k1ilqpvh3he7tc3o1xr2.png", "0,002 kg CO2e / km"),
    Item("4", "climatisation", "Valeurs exprimées en kg CO2e émis par produit comprenant la fabrication, la distribution et l’usage. En même temps qu’elle refroidit l’air intérieur, réchauffe l’air extérieur.", +200, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1702006824/jsehodpw39q6o6kdh62p.png", "413,17 kg CO2e / unité"),
    Item("5", "Voiture", "Valeurs exprimées en kg CO2e émis par personne en France. Sont incluses les émissions directes, la construction des véhicules (fabrication, maintenance et fin de vie) et la production et distribution de carburant et d'électricité. La construction des infrastructures (routes, rails, aéroports...) n'est pas incluse. Les voitures personnelles sont l'un des principaux pollueurs puisqu’elles représentent 60,6 % des émissions totales de CO2 dues au transport routier en Europe.", +150, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1702006768/esmaxigtlleb5vsf5z9j.png", "0,22 kg CO2e / km"),
    Item("6", "Viande steak", "Valeurs exprimées en kg CO2e émis par repas comprenant la fabrication, la distribution et la consommation. La production de viande, en particulier de bœuf, a un bilan carbone élevé en raison de l'élevage intensif, de l'alimentation des animaux, du transport, de la déforestation et de la gestion des déchets. Réduire la consommation de viande et soutenir des pratiques durables sont des moyens efficaces de réduire l'impact environnemental.", +50, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1702006610/piqsqxmtghsinbz8mqgl.png", "7,26 kg CO2e / repas"),
    Item("7", "Smartphone", "Valeurs exprimées en kg CO2e émis par produit comprenant la fabrication, la distribution et l'usage. La production de smartphones a un bilan carbone élevé en raison de l'extraction des matériaux, de la fabrication, de la consommation d'énergie et du transport. Prolonger la durée de vie des téléphones, recycler les anciens modèles et choisir des appareils écoénergétiques sont des moyens de réduire leur impact environnemental.", +100, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1702007073/ws0awhwldz2dpx8enth8.png", "29,24 kg CO2e / unité"),
    Item("8", "Repas végétalien", "Les repas végétaliens ont généralement une empreinte carbone plus faible que les repas contenant de la viande en raison de l'absence d'élevage animal. Cependant, l'empreinte carbone d'un repas végétalien dépend des aliments spécifiques choisis et de leur mode de production. Opter pour des aliments locaux, de saison, cultivés de manière durable et peu transformés peut réduire davantage l'impact environnemental de votre repas végétalien.", -20, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1701999454/c2lj8lzqq9nr1ouxujbb.png", "0,51 kg CO2e / repas"),
    Item("9", "Avion", "Les voyages en avion ont une empreinte carbone élevée en raison de la combustion de carburant et des émissions de gaz à effet de serre associées.", +300, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1701999778/fri8rqsh1gijirdlpebz.png", "0,23 kg CO2e / km"),
    Item("10", "Industrie pétrolière", "L'extraction et le raffinage du pétrole ont une empreinte carbone élevée en raison de la combustion du pétrole et du gaz naturel.", +400, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1701998711/jr4iixok7sjmzqpe8jbf.png", "Pas de valeur précise mais impact catastrophique."),
    Item("11", "Fast-food", "Les chaînes de restauration rapide ont souvent une empreinte carbone élevée en raison de l'utilisation de viande et d'emballages à usage unique.", +40, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1701998789/ysjzxvgduclmmheihmpj.png", "7,26 kg CO2e / repas"),
    Item("12", "Récupération et recyclage", "La réutilisation, le recyclage et la réduction des déchets contribuent à réduire les émissions liées à la production de nouveaux matériaux.", -40, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1701999093/nkznevkhxmz3osgn5sec.png", "Chaque étude montre que le recyclage et la réutilisation ont des effets positifs sur la réduction des gaz à effet de serre, principalement par la récupération de l'énergie, de l'eau et des matériaux utilisés pour fabriquer ces produits."),
    Item("14", "Bus", "Les autobus ont un bilan carbone plus favorable que les voitures individuelles en raison de leur capacité à transporter de nombreux passagers à la fois, réduisant ainsi l'empreinte carbone par personne transportée. Ils émettent également moins de gaz à effet de serre par kilomètre parcouru, en particulier s'ils utilisent des carburants propres ou des technologies électriques. Les systèmes de bus efficaces encouragent l'utilisation des transports en commun et contribuent à la réduction des émissions liées à la circulation automobile.", -10, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1701998197/tzzjfoix4jpxk8zu9i9k.png", "0,11 kg CO2e / km"),
    Item("15", "Cigarette", "La cigarette a un impact environnemental négatif en contribuant à la déforestation, à l'utilisation d'engrais chimiques, à la pollution de l'eau, aux émissions de gaz à effet de serre dans la production et la combustion, à la génération de déchets toxiques (mégots), et aux risques d'incendies de forêt. Bien que son impact individuel soit limité, l'ensemble du cycle de vie du tabac a un effet cumulatif sur le climat et l'environnement, soulignant l'importance de réduire la consommation de tabac pour des raisons de santé et environnementales.", +20, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1701999710/htepgtinse4pjqa7xcbs.png", "0,01 kg CO2e / unité"),
    Item("16", "Carotte", "Pas très émetteur,  les carottes ont un bilan carbone relativement faible par rapport à de nombreux autres aliments, en particulier si elles sont cultivées localement et de manière durable. Le fait de privilégier les carottes produites localement et de saison, ainsi que de réduire les déchets alimentaires, peut contribuer à réduire l'impact environnemental des carottes que vous consommez.", -20, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1701998004/psn9u0duefaru0ndow5b.png", "0,36 kg CO2e / kg"),
    Item("17", "Champignon", "Les champignons ont effectivement une empreinte carbone relativement faible. Ils nécessitent moins d'espace et de ressources pour leur culture par rapport à de nombreuses autres cultures alimentaires. De plus, les champignons peuvent être cultivés sur des substrats qui seraient autrement considérés comme des déchets, tels que le marc de café ou les copeaux de bois, ce qui en fait une option durable et respectueuse de l'environnement.", -20, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1701997952/xka8dgbztabwz8o9dszf.png", "0,49 kg CO2e / kg"),
    Item("18", "Transport en vélo ou à pied", "Émissions nulles comparées aux véhicules motorisés.", -50, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1701997886/alhpuzxhdbawqabmkwuw.png", "0 kg co2 / kg"),
    Item("19", "Bouteilles en plastique", "Leur production et leur élimination sont très polluantes.", +30, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1701997826/bjmic2xihxyzitengppm.png", "0,27 kg CO2e / litre"),
    Item("20", "Mangue", "L'empreinte carbone d'une mangue exportée par avion est élevée en raison de la consommation importante de carburant associée au transport aérien sur de longues distances. Ce mode de transport génère des émissions significatives de gaz à effet de serre. Pour réduire l'empreinte carbone, il est préférable de choisir des fruits cultivés localement et en saison, qui ont tendance à avoir une empreinte carbone moindre. Cela contribue à minimiser l'impact environnemental associé à l'importation de mangues par avion.", +10, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1701999821/giytewy2lnrna6kwipq7.webp", "10,64 kg CO2e / kg"),
    Item("21", "Voitures électriques avec batteries à base de métaux rares", "L'extraction de métaux rares comme le lithium et le cobalt est souvent associée à des pratiques minières non durables. Cela peut entraîner la dégradation des écosystèmes locaux, la pollution de l'eau et des sols, ainsi que des conditions de travail précaires dans les mines. Bien que les voitures électriques contribuent à réduire les émissions pendant leur utilisation, il est essentiel de prendre en compte l'ensemble du cycle de vie, y compris la production des batteries.", +30, "http://res.cloudinary.com/dazguhihs/image/upload/v1702014807/r8dw71vy40ldke9545vu.png", "12-18 kg CO2e / kg de batterie"),
    Item("22", "Bioplastiques", "La production de bioplastiques à partir de cultures agricoles peut entraîner la déforestation, la conversion de terres agricoles et la perte de biodiversité. De plus, le processus de transformation des plantes en bioplastiques peut nécessiter des ressources énergétiques importantes. Il est donc crucial de considérer les implications environnementales globales de la production de bioplastiques", +15, "http://res.cloudinary.com/dazguhihs/image/upload/v1702014806/afymurdba3ck64pssp9l.png", "Variable en fonction des matières premières, mais généralement inférieur à celui des plastiques traditionnels."),
    Item("23", "Centrales électriques biomasse", "Cependant, l'utilisation de biomasse peut avoir des impacts négatifs locaux, notamment la déforestation et la conversion d'écosystèmes naturels en cultures énergétiques. Ces changements peuvent entraîner la perte de biodiversité et la libération de carbone stocké dans les sols et la végétation, contrebalançant ainsi les avantages climatiques potentiels", +5, "http://res.cloudinary.com/dazguhihs/image/upload/v1702014806/xax0snudzeg4r4evyfct.png", "1Variable en fonction des sources de biomasse et des technologies utilisées, mais généralement considéré comme neutre en carbone sur une base mondiale."),
    Item("24", "Énergie éolienne", "Les éoliennes ont des avantages significatifs en termes de réduction des émissions de CO2 pendant leur cycle de vie. Cependant, certains aspects doivent être pris en compte, tels que les émissions liées à la fabrication des matériaux des éoliennes, la nécessité de terres pour l'installation, et les préoccupations liées aux impacts sur la faune, notamment les oiseaux et les chauves-souris. Le taux de CO2 ici prend en compte la fabrication des éoliennes, la construction des fondations, l'assemblage des composants, et le transport.", +200, "https://res.cloudinary.com/dfkkgyk5w/image/upload/v1702006140/uwkatu1jujj7fg7euohz.png", "11-25 g CO2e / kWh"),
    Item("25", "Énergie solaire", "L'énergie solaire est une source d'énergie propre pendant son utilisation. Cependant, la fabrication des panneaux solaires implique l'extraction de métaux rares et de matériaux potentiellement toxiques. De plus, la gestion des déchets électroniques à la fin de la vie des panneaux solaires représente un défi environnemental. Les progrès dans la recyclabilité des panneaux solaires sont en cours pour atténuer cet impact. Le taux de CO2 ici prend en compte la fabrication des panneaux solaires, le processus d'assemblage, et le transport.", +180, "http://res.cloudinary.com/dazguhihs/image/upload/v1702014805/shptdmfqmkvo97qqcvk3.png", "20-60 g CO2e / kWh"),
  )

  // Méthode pour lister tous les items
  // Future est utilisé pour rendre la méthode asynchrone
  def list(): Future[List[Item]] = Future {
    items
  }

  // Méthode pour obtenir un item par ID
  def get(id: String): Future[Option[Item]] = Future {
    logger.trace(s"get: id = $id")
    items.find(_.id == id)
  }

  // Methode pour obtenir un item par son nom
  def getByName(name: String): Future[Option[Item]] = Future {
    logger.trace(s"get: name = $name")
    items.find(_.name == name)
  }

  // Méthode pour créer un nouvel item
  // Non utilisé dans ce projet
  def create(item: Item): Future[Unit] = Future {
    items = items :+ item
  }
}
